"use client";
import "./globals.css";
import Header from "./components/Header";
import localfont from "next/font/local";
import SubForm from "./components/SubForm";
import Footer from "./components/Footer";
import HeaderTop from "./components/HeaderTop";
import { FavouritesProvider } from "./context/FavouritesContext";
import { BasketProvider } from "./context/BasketContext";

const montserrat = localfont({
  src: [
    {
      path:'../public/fonts/Montserrat-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path:'../public/fonts/Montserrat-SemiBold.ttf',
      weight: '600',
      style: 'normal'
    },
  ],
})
export const metadata = {
  title: "Ad Marginem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}> 
        <BasketProvider>
          <FavouritesProvider>
            <HeaderTop />
            <Header />
            <main className="container m-auto">{children}</main>
            <SubForm />
            <Footer />
          </FavouritesProvider>
        </BasketProvider>
      </body>
    </html>
  );
}
