"use client";
import "./globals.css";
import Header from "./components/Header";
import localfont from "next/font/local";
import SubForm from "./components/SubForm";
import Footer from "./components/Footer";
import HeaderTop from "./components/HeaderTop";
import { FavouritesProvider } from "./context/FavouritesContext";
import { BasketProvider } from "./context/BasketContext";
const myFont = localfont({ src: "../public/fonts/IBMPlexSans-Regular.ttf" });

export const metadata = {
  title: "Ad Marginem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <BasketProvider>
          <FavouritesProvider>
            <HeaderTop />
            <Header />
            <main className="container m-auto">{children}</main>
            <SubForm />
            <Footer />
          </FavouritesProvider>
        </BasketProvider>
      </body>
    </html>
  );
}
